[
  {
    name: "Scooter cult",
    provider: "Agency_1",
    rating: 4.25,
    category: "Scooter",
    model: "SC 2017",
    price: "220",
    description:
      "is a motorcycle with an underbone or step-through frame and a platform for the rider's feet, emphasizing comfort and fuel economy. Elements of scooter design were present in some of the earliest motorcycles, and scooters have been made since at least 1914. Scooter development continued in Europe and the United States between the World Wars. ",
    status: "false",
    type: "family",
    seat: "normal",
    color: "black",
    weight: "12kg",
  },
  {
    name: "Scooter cult",
    provider: "Agency_1",
    rating: 4.25,
    category: "Scooter",
    model: "SC 2017",
    price: "220",
    description:
      "is a motorcycle with an underbone or step-through frame and a platform for the rider's feet, emphasizing comfort and fuel economy. Elements of scooter design were present in some of the earliest motorcycles, and scooters have been made since at least 1914. Scooter development continued in Europe and the United States between the World Wars. ",
    status: "false",
    type: "family",
    seat: "normal",
    color: "black",
    weight: "12kg",
  },
  {
    name: "Scooter cult",
    provider: "Agency_1",
    rating: 4.25,
    category: "Scooter",
    model: "SC 2017",
    price: "220",
    description:
      "is a motorcycle with an underbone or step-through frame and a platform for the rider's feet, emphasizing comfort and fuel economy. Elements of scooter design were present in some of the earliest motorcycles, and scooters have been made since at least 1914. Scooter development continued in Europe and the United States between the World Wars. ",
    status: "false",
    type: "family",
    seat: "normal",
    color: "black",
    weight: "12kg",
  },
];